color: null
fieldLayouts:
  e65bd1e5-abf6-43e6-a3f0-2fbb329e35c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 24bd1247-7ed2-48e8-af76-5b8ffc486ef6 # Content Blocks - CTA Caption - Heading
            handle: heading
            includeInCards: true
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1723daa2-1605-463e-bb38-4472e9bcfaf4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c274864-9cf0-4ef9-b4bd-88da544515ad # Content Blocks - CTA Caption - Information
            handle: null
            includeInCards: false
            instructions: null
            label: Information
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 521a42a3-5a35-43b3-9c62-129f039d3229
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ee9b9a7-d12d-4c9b-b069-586609cb5ea9 # Content Blocks - CTA Caption - Link Label
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link Label'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b81b8ef-34cb-4cb8-9355-666bc5398c21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b1b9f85-3554-4b4a-8d39-467bf5e4a35d # Content Blocks - CTA Caption - Internal Link
            handle: null
            includeInCards: false
            instructions: null
            label: 'Internal Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79e1cd1c-b273-4ae7-91d1-ca890d25eaf6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55c6cb51-defc-4e30-bc18-e524de65b7b7 # Content Blocks - CTA Caption - External Link
            handle: null
            includeInCards: false
            instructions: null
            label: 'External Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82dcbab5-40bc-4e35-b60c-5c82732a9e90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42ad64e7-b07b-4601-9e6b-2d21bc0fe5d8 # Content Blocks - CTA Caption - Link Icon
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link Icon'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37e5a668-9ae1-4caf-b8d9-a2335cab28eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ba28a66-d3aa-4c97-ad77-8e26087b3d70 # Content Blocks - CTA Caption - Narrow Width
            handle: null
            includeInCards: false
            instructions: null
            label: 'Narrow Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 892da9c7-a6ed-4d7c-9e8c-3073f53d5fe2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e6c3502-8203-4d4f-a932-fa343b17b998
        userCondition: null
handle: ctaCaption
hasTitleField: false
icon: null
name: 'CTA Caption'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
