color: orange
description: null
fieldLayouts:
  e65bd1e5-abf6-43e6-a3f0-2fbb329e35c4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-18T22:28:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cf7038b3-3aa7-4d1f-8a12-1cf0017d5b2c # Heading
            handle: null
            includeInCards: true
            instructions: 'Allows HTML & Twig syntax.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1723daa2-1605-463e-bb38-4472e9bcfaf4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-18T22:28:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8c274864-9cf0-4ef9-b4bd-88da544515ad # Details
            handle: null
            includeInCards: true
            instructions: null
            label: Information
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 521a42a3-5a35-43b3-9c62-129f039d3229
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-18T22:28:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 55c6cb51-defc-4e30-bc18-e524de65b7b7 # Link Destination
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82dcbab5-40bc-4e35-b60c-5c82732a9e90
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-18T22:28:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42ad64e7-b07b-4601-9e6b-2d21bc0fe5d8 # Link Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37e5a668-9ae1-4caf-b8d9-a2335cab28eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-18T22:28:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0ba28a66-d3aa-4c97-ad77-8e26087b3d70 # Layout Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 892da9c7-a6ed-4d7c-9e8c-3073f53d5fe2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e6c3502-8203-4d4f-a932-fa343b17b998
        userCondition: null
handle: ctaCaption
hasTitleField: false
icon: megaphone
name: 'CTA Caption'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
