color: null
fieldLayouts:
  5bb81956-9103-4bdb-99ce-02ab032ec5f5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 71e35861-1096-4d5b-b5e8-47ad200b20c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f36520a3-472b-40e0-8895-6f577f213037 # Attachment
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03178f87-bb08-47b2-9bdb-fb5d23d2827d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e2c0abf4-734d-4c22-bde5-d4c88e065840
        userCondition: null
handle: embed
hasTitleField: false
icon: cubes
name: Embed
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
