color: null
description: null
fieldLayouts:
  268b8d62-05d6-417a-9a6b-ed707ea8dd4b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-18T01:05:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8b78b8de-8c42-4fb9-93e2-aac6c4b6fa48
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-18T01:05:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85c4431d-c47e-4f71-be6f-822a361ea08f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-20T23:50:46+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d5f9dfc1-94a1-4dc2-8bd9-e0572c4fa2a9
            userCondition: null
          -
            dateAdded: '2025-11-20T23:50:46+00:00'
            elementCondition: null
            heading: Timing
            type: craft\fieldlayoutelements\Heading
            uid: ab4920c8-a332-4dd2-9a07-660fde8c6bbb
            userCondition: null
          -
            dateAdded: '2025-11-20T23:50:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ceeaad1b-ea68-46f6-8b14-e1c219b9a828 # Start Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1e44ddd-f9f9-42fe-bbf2-654ad6b558fe
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-20T23:50:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e565f693-e816-4539-8caf-a618b5637ea4 # End Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc2af75e-98d0-4a88-a3ca-89ab4cd92476
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-20T23:50:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 81b9e710-5a36-4bb3-9b2e-f11804cfc14d # Date Expression
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b63be30-ad78-40ae-8311-91edf2ea3129
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-20T23:50:46+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 47afb268-2344-4e1e-a559-c5dd57f444a8
            userCondition: null
          -
            dateAdded: '2025-11-18T01:05:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8f20da1-e003-4558-b94c-6fbb7d93e290
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5bb95504-52d1-421b-96ad-250b124e139a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-18T01:05:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c8da1bd9-67c9-402f-8a95-aeaec337e207 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d261b3b2-bb97-447e-9647-a7e5f6cbcba1
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 101d8795-8da3-4a62-ae6b-0217fac54d72
        userCondition: null
handle: exhibit
hasTitleField: true
icon: calendar-image
name: Exhibit
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
uiLabelFormat: '{title}'
