color: null
fieldLayouts:
  74ad9d74-87f7-47ce-979e-cd93cc0f6002:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d7b7e2f-71b1-4b25-8501-c8edc07a7f18 # Content Blocks - Google Map Embed - Embed Code
            handle: null
            includeInCards: true
            instructions: null
            label: 'Embed Code'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f06ea1f6-4c5b-459b-8c6c-42fcbc6ab114
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1bda72d4-5ac2-4da7-80b2-e764095687ce
        userCondition: null
handle: googleMapEmbed
hasTitleField: false
icon: null
name: 'Google Map Embed'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
