color: null
description: null
fieldLayouts:
  10b19456-af43-4ddc-95ec-daf105ffcc38:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: a32535ef-ef8d-4801-980f-19499eb7b6f4
        userCondition: null
handle: styleguide
hasTitleField: false
icon: hammer-brush
name: Styleguide
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: none
uiLabelFormat: '{title}'
