allowPublicRegistration: false
deactivateByDefault: false
defaultGroup: ''
photoSubpath: null
photoVolumeUid: e2717149-0d53-46cf-ac19-1ae155f7d8e3 # User Photos
require2fa: false
requireEmailVerification: true
validateOnPublicRegistration: false
