defaultPlacement: end
fieldLayouts:
  98cfb40e-e148-4f7a-9fc3-8d62399a5f5a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: f1a0bf84-c804-4a36-b0be-8058429671c8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75f49f5a-f102-49d0-b187-23d7cc25df13
        userCondition: null
handle: newsCategory
name: 'News Category'
siteSettings:
  6e97e2c0-ef1f-4536-9e8b-a05daae74a8f: # Lisboa
    hasUrls: true
    template: _/pages/news
    uriFormat: 'news/category/{slug}'
  78e46d3b-f39e-4de2-8a7c-a899cebca7aa:
    hasUrls: true
    template: _/pages/news
    uriFormat: 'news/category/{slug}'
  752481c4-0191-42fe-aedd-fbdf302d3eb9: # Global
    hasUrls: true
    template: _/pages/news
    uriFormat: 'news/category/{slug}'
  ba1b402d-782f-4f88-9747-2f698adfc9e2: # London
    hasUrls: true
    template: _/pages/news
    uriFormat: 'news/category/{slug}'
  beffd6f6-3f04-4ae0-b2c6-71a4e419ab57: # Paris
    hasUrls: true
    template: _/pages/news
    uriFormat: 'news/category/{slug}'
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9: # Barçalona
    hasUrls: true
    template: _/pages/news
    uriFormat: 'news/category/{slug}'
structure:
  maxLevels: null
  uid: 7e72aa7b-bf24-45c1-96f8-48a62b753660
