columnSuffix: null
handle: darkUI
instructions: null
name: 'Content Blocks - Slider - Dark UI'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
