columnSuffix: null
handle: dateStart
instructions: null
name: 'Start Date'
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
