columnSuffix: null
handle: description
instructions: null
name: 'Content Blocks - Stats and Image - Description'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 40bfb363-8740-499a-82f2-6eda20cb6025 # Vhc No Assets
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
