columnSuffix: null
handle: embedCode
instructions: 'Paste your HTML here.'
name: 'Embed Code'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
