columnSuffix: null
handle: embedCode
instructions: 'Go to Google Maps, find a location, click the "Share" button, click "Embed a map", click "Copy HTML", then paste into the text box below.'
name: 'Content Blocks - Google Map Embed - Embed Code'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
