columnSuffix: null
handle: featuredExhibits
instructions: 'Will be displayed in a random order.'
name: 'Featured Exhibits'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 4
  minRelations: null
  selectionLabel: null
  showCardsInGrid: true
  showSiteMenu: true
  sources:
    - 'section:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
