columnSuffix: null
handle: heroTitle
instructions: 'This page’s canonical title is determined by its section settings. Use this field to override it at the top of the page.'
name: 'Hero Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
