columnSuffix: null
handle: newsCategory
instructions: null
name: 'News Category'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: 1
  defaultPlacement: end
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  source: 'group:6b0e8c8f-3b9a-440d-b5ad-e209cd4eb486' # News Category
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
