columnSuffix: null
handle: richText
instructions: null
name: 'Rich Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes:
    - a36fa6aa-4824-448f-82cf-b3086f8582c5 # Images
  characterLimit: null
  ckeConfig: a6cb7c13-e866-45ba-ad8e-a44c552ff6c1 # Rich Text
  createButtonLabel: null
  defaultTransform: 4ee7fd54-73f7-4abe-94e3-6c01585ca5e3 # Inline
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 386be967-b947-414c-8ea0-824e977d04ad # Embed
  expandEntryButtons: false
  fullGraphqlData: false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  showWordCount: false
  sourceEditingGroups: null
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
