columnSuffix: null
handle: successMessage
instructions: 'Optional success message displayed when the attached form is submitted.'
name: 'Success Message'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
