description: 'Additional permissions for anyone who needs to manage the site’s code or configuration, in production. This is _not_ the equivalent of Craft’s **Admin** designation.'
handle: developers
name: Developers
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-freeform
  - accessplugin-seomatic
  - accesssitewhensystemisoff
  - 'editglobalset:a90cc22d-485c-4cd7-a4b9-63a8a637e90d' # Navigation
  - freeform-access-quick-export
  - freeform-formsaccess
  - freeform-formscreate
  - freeform-formsdelete
  - freeform-formsmanage
  - 'freeform-formsmanage:5'
  - freeform-formsmanageindividual
  - freeform-integrationsaccess
  - freeform-integrationsmanage
  - freeform-notificationsaccess
  - freeform-notificationsmanage
  - freeform-pdftemplatesaccess
  - freeform-pdftemplatesmanage
  - freeform-pro-exportnotificationsaccess
  - freeform-pro-exportnotificationsmanage
  - freeform-pro-exportprofilesaccess
  - freeform-pro-exportprofilesmanage
  - freeform-settingsaccess
  - freeform-submissionsaccess
  - freeform-submissionsmanage
  - 'freeform-submissionsmanage:5'
  - freeform-submissionsmanageindividual
  - freeform-submissionsread
  - 'freeform-submissionsread:5'
  - freeform-submissionsreadindividual
  - 'seomatic:content-meta'
  - 'seomatic:content-meta:facebook'
  - 'seomatic:content-meta:general'
  - 'seomatic:content-meta:sitemap'
  - 'seomatic:content-meta:twitter'
  - 'seomatic:dashboard'
  - 'seomatic:global-meta'
  - 'seomatic:global-meta:ads'
  - 'seomatic:global-meta:facebook'
  - 'seomatic:global-meta:general'
  - 'seomatic:global-meta:humans'
  - 'seomatic:global-meta:robots'
  - 'seomatic:global-meta:security'
  - 'seomatic:global-meta:twitter'
  - 'seomatic:plugin-settings'
  - 'seomatic:site-settings'
  - 'seomatic:site-settings:creator'
  - 'seomatic:site-settings:identity'
  - 'seomatic:site-settings:miscellaneous'
  - 'seomatic:site-settings:sitemap'
  - 'seomatic:site-settings:social'
  - 'seomatic:tracking-scripts'
  - 'seomatic:tracking-scripts:facebookpixel'
  - 'seomatic:tracking-scripts:fathom'
  - 'seomatic:tracking-scripts:googleanalytics'
  - 'seomatic:tracking-scripts:googletagmanager'
  - 'seomatic:tracking-scripts:gtag'
  - 'seomatic:tracking-scripts:hubspot'
  - 'seomatic:tracking-scripts:linkedininsight'
  - 'seomatic:tracking-scripts:matomo'
  - 'seomatic:tracking-scripts:pinteresttag'
  - 'seomatic:tracking-scripts:plausible'
  - 'utility:asset-indexes'
  - 'utility:clear-caches'
  - 'utility:db-backup'
  - 'utility:deprecation-errors'
  - 'utility:find-replace'
  - 'utility:migrations'
  - 'utility:php-info'
  - 'utility:queue-manager'
  - 'utility:system-messages'
  - 'utility:system-report'
  - 'utility:updates'
