description: null
handle: siteAdministrators
name: 'Site Administrators'
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-freeform
  - accessplugin-seomatic
  - accesssitewhensystemisoff
  - administrateusers
  - 'assignusergroup:2baf1b70-dad1-4c27-b485-a94b23a3e89f' # Site Administrators
  - 'assignusergroup:823ac85e-6b3c-499a-bbdc-99a4e2432138' # Content Managers
  - assignuserpermissions
  - 'createentries:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'createentries:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - 'createfolders:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'deleteassets:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'deletecategories:6b0e8c8f-3b9a-440d-b5ad-e209cd4eb486' # News Category
  - 'deleteentries:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'deleteentries:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - 'deletepeerassets:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'deletepeercategorydrafts:6b0e8c8f-3b9a-440d-b5ad-e209cd4eb486' # News Category
  - 'deletepeerentries:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'deletepeerentries:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - 'deletepeerentrydrafts:0edb3240-3f53-4f13-a789-2bd0b6cae755' # Styleguide
  - 'deletepeerentrydrafts:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'deletepeerentrydrafts:8a02b167-35d9-4c71-bc4b-59ee401246e3' # Visit
  - 'deletepeerentrydrafts:8f6c3046-e9ee-4df9-af84-6dc0199f01da' # Contact
  - 'deletepeerentrydrafts:977f4737-eaaa-4d0f-aadb-10251ee1c4ff' # About
  - 'deletepeerentrydrafts:9b80c4d3-7a27-4bc4-af25-742e6cf5f77a' # News
  - 'deletepeerentrydrafts:9d1ed50c-2239-4171-8b5a-ab121973301f' # Home
  - 'deletepeerentrydrafts:b39c0003-6393-4175-8698-6edef920f7fd' # Exhibitions
  - 'deletepeerentrydrafts:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - deleteusers
  - 'editglobalset:a90cc22d-485c-4cd7-a4b9-63a8a637e90d' # Navigation
  - 'editimages:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'editpeerimages:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - editusers
  - freeform-access-quick-export
  - freeform-dashboardaccess
  - freeform-fieldsaccess
  - freeform-fieldsmanage
  - freeform-formsaccess
  - freeform-formsmanage
  - freeform-integrationsaccess
  - freeform-integrationsmanage
  - freeform-notificationsaccess
  - freeform-notificationsmanage
  - freeform-pro-exportprofilesaccess
  - freeform-pro-exportprofilesmanage
  - freeform-resources
  - freeform-settingsaccess
  - freeform-submissionsaccess
  - freeform-submissionsmanage
  - impersonateusers
  - moderateusers
  - performupdates
  - registerusers
  - 'replacefiles:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'replacepeerfiles:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'saveassets:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'savecategories:6b0e8c8f-3b9a-440d-b5ad-e209cd4eb486' # News Category
  - 'saveentries:0edb3240-3f53-4f13-a789-2bd0b6cae755' # Styleguide
  - 'saveentries:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'saveentries:8a02b167-35d9-4c71-bc4b-59ee401246e3' # Visit
  - 'saveentries:8f6c3046-e9ee-4df9-af84-6dc0199f01da' # Contact
  - 'saveentries:977f4737-eaaa-4d0f-aadb-10251ee1c4ff' # About
  - 'saveentries:9b80c4d3-7a27-4bc4-af25-742e6cf5f77a' # News
  - 'saveentries:9d1ed50c-2239-4171-8b5a-ab121973301f' # Home
  - 'saveentries:b39c0003-6393-4175-8698-6edef920f7fd' # Exhibitions
  - 'saveentries:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - 'savepeerassets:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'savepeercategorydrafts:6b0e8c8f-3b9a-440d-b5ad-e209cd4eb486' # News Category
  - 'savepeerentries:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'savepeerentries:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - 'savepeerentrydrafts:0edb3240-3f53-4f13-a789-2bd0b6cae755' # Styleguide
  - 'savepeerentrydrafts:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'savepeerentrydrafts:8a02b167-35d9-4c71-bc4b-59ee401246e3' # Visit
  - 'savepeerentrydrafts:8f6c3046-e9ee-4df9-af84-6dc0199f01da' # Contact
  - 'savepeerentrydrafts:977f4737-eaaa-4d0f-aadb-10251ee1c4ff' # About
  - 'savepeerentrydrafts:9b80c4d3-7a27-4bc4-af25-742e6cf5f77a' # News
  - 'savepeerentrydrafts:9d1ed50c-2239-4171-8b5a-ab121973301f' # Home
  - 'savepeerentrydrafts:b39c0003-6393-4175-8698-6edef920f7fd' # Exhibitions
  - 'savepeerentrydrafts:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - 'utility:asset-indexes'
  - 'utility:clear-caches'
  - 'utility:db-backup'
  - 'utility:deprecation-errors'
  - 'utility:find-replace'
  - 'utility:migrations'
  - 'utility:php-info'
  - 'utility:queue-manager'
  - 'utility:system-messages'
  - 'utility:system-report'
  - 'utility:updates'
  - 'viewassets:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'viewcategories:6b0e8c8f-3b9a-440d-b5ad-e209cd4eb486' # News Category
  - 'viewentries:0edb3240-3f53-4f13-a789-2bd0b6cae755' # Styleguide
  - 'viewentries:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'viewentries:8a02b167-35d9-4c71-bc4b-59ee401246e3' # Visit
  - 'viewentries:8f6c3046-e9ee-4df9-af84-6dc0199f01da' # Contact
  - 'viewentries:977f4737-eaaa-4d0f-aadb-10251ee1c4ff' # About
  - 'viewentries:9b80c4d3-7a27-4bc4-af25-742e6cf5f77a' # News
  - 'viewentries:9d1ed50c-2239-4171-8b5a-ab121973301f' # Home
  - 'viewentries:b39c0003-6393-4175-8698-6edef920f7fd' # Exhibitions
  - 'viewentries:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - 'viewpeerassets:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
  - 'viewpeercategorydrafts:6b0e8c8f-3b9a-440d-b5ad-e209cd4eb486' # News Category
  - 'viewpeerentries:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'viewpeerentries:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - 'viewpeerentrydrafts:0edb3240-3f53-4f13-a789-2bd0b6cae755' # Styleguide
  - 'viewpeerentrydrafts:666bcffb-61d7-43b4-a9f5-8c51c458b356' # News Articles
  - 'viewpeerentrydrafts:8a02b167-35d9-4c71-bc4b-59ee401246e3' # Visit
  - 'viewpeerentrydrafts:8f6c3046-e9ee-4df9-af84-6dc0199f01da' # Contact
  - 'viewpeerentrydrafts:977f4737-eaaa-4d0f-aadb-10251ee1c4ff' # About
  - 'viewpeerentrydrafts:9b80c4d3-7a27-4bc4-af25-742e6cf5f77a' # News
  - 'viewpeerentrydrafts:9d1ed50c-2239-4171-8b5a-ab121973301f' # Home
  - 'viewpeerentrydrafts:b39c0003-6393-4175-8698-6edef920f7fd' # Exhibitions
  - 'viewpeerentrydrafts:c49dac11-102e-429e-8bcc-5c8d99508dcb' # Exhibits
  - viewusers
