defaultPlacement: end
enableVersioning: true
entryTypes:
  - d703e6d3-677f-4b60-99d7-44b4710ff7bc # Contact
handle: contact
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9: # English
    enabledByDefault: true
    hasUrls: true
    template: _/pages/contact
    uriFormat: contact
type: single
