defaultPlacement: end
enableVersioning: true
entryTypes:
  - 0b3ab84a-728c-4dfa-b505-ee524b9631d9 # Home
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9: # English
    enabledByDefault: true
    hasUrls: true
    template: _/pages/home
    uriFormat: __home__
type: single
