defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 19f3873e-d59d-48d0-bbee-1c25acd90c6c # News
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9: # English
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news
    uriFormat: news
type: single
