defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 19f3873e-d59d-48d0-bbee-1c25acd90c6c # News
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6e97e2c0-ef1f-4536-9e8b-a05daae74a8f: # Lisbon
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news
    uriFormat: news
  ba1b402d-782f-4f88-9747-2f698adfc9e2: # London
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news
    uriFormat: news
  beffd6f6-3f04-4ae0-b2c6-71a4e419ab57: # Paris
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news
    uriFormat: news
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9: # Barçalona
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news
    uriFormat: news
type: single
