defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f4cfbdf3-fa41-42c6-99f5-d0efefc2e406 # News Article
handle: newsArticles
maxAuthors: 1
name: 'News Articles'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
  -
    label: 'Listing page'
    refresh: '1'
    urlFormat: news
propagationMethod: custom
siteSettings:
  6e97e2c0-ef1f-4536-9e8b-a05daae74a8f: # Lisboa
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news-article
    uriFormat: 'news/{slug}'
  ba1b402d-782f-4f88-9747-2f698adfc9e2: # London
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news-article
    uriFormat: 'news/{slug}'
  beffd6f6-3f04-4ae0-b2c6-71a4e419ab57: # Paris
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news-article
    uriFormat: 'news/{slug}'
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9: # Barçalona
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news-article
    uriFormat: 'news/{slug}'
type: channel
